#include "mmq_id_common.cuh"

DECL_MMQ_CASE(GGML_TYPE_Q4_0);
DECL_MMQ_CASE(GGML_TYPE_Q4_1);
DECL_MMQ_CASE(GGML_TYPE_Q5_0);
DECL_MMQ_CASE(GGML_TYPE_Q5_1);
DECL_MMQ_CASE(GGML_TYPE_Q8_0);
DECL_MMQ_CASE(GGML_TYPE_MXFP4);
DECL_MMQ_CASE(GGML_TYPE_Q2_K);
DECL_MMQ_CASE(GGML_TYPE_Q3_K);
DECL_MMQ_CASE(GGML_TYPE_Q4_K);
DECL_MMQ_CASE(GGML_TYPE_Q5_K);
DECL_MMQ_CASE(GGML_TYPE_Q6_K);
DECL_MMQ_CASE(GGML_TYPE_IQ2_XXS);
DECL_MMQ_CASE(GGML_TYPE_IQ2_XS);
DECL_MMQ_CASE(GGML_TYPE_IQ2_S);
DECL_MMQ_CASE(GGML_TYPE_IQ3_XXS);
DECL_MMQ_CASE(GGML_TYPE_IQ3_S);
DECL_MMQ_CASE(GGML_TYPE_IQ1_S);
DECL_MMQ_CASE(GGML_TYPE_IQ4_NL);
DECL_MMQ_CASE(GGML_TYPE_IQ4_XS);

