#if defined(GGML_USE_HIPBLAS) && defined(__HIP_PLATFORM_AMD__)
#include "mmvq-args.h"
void mul_mat_vec_iq1_bn_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq1_kt_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq1_m_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq1_m_r4_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq1_s_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq1_s_r4_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq2_bn_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq2_k_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq2_k_r4_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq2_kl_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq2_ks_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq2_kt_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq2_s_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq2_xs_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq2_xxs_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq3_k_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq3_k_r4_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq3_ks_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq3_kt_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq3_s_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq3_xxs_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq4_k_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq4_k_r4_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq4_ks_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq4_ks_r4_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq4_kss_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq4_kt_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq4_nl_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq4_xs_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq5_k_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq5_k_r4_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq5_ks_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq5_ks_r4_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_iq6_k_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_mxfp4_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_q2_K_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_q3_K_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_q4_0_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_q4_1_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_q4_K_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_q5_0_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_q5_1_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_q5_K_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_q6_0_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_q6_K_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
void mul_mat_vec_q8_0_q8_1_cuda(const mmvq_args & args, cudaStream_t stream) { GGML_UNUSED(args); GGML_UNUSED(stream); }
#endif // defined(GGML_USE_HIPBLAS) && defined(__HIP_PLATFORM_AMD__)
